### ISSUE TITLE
Line selection with Shift+End includes the newline

### ISSUE THREAD

**Issue by char101** [Androthi/SavageEd#1]
Hi,

When selecting a line by placing the cursor at the start and then pressing Shift+End, and then pressing Ctrl+C, the newline is included in the selection. Normally line selection does not included the newline.

Thanks.

**Comment by Androthi** [comment]
This is the default behavior of 32bit Richedit 2.0 (I have not made any changes to what it does with shift-end). Looks like the modern version of Richedit and newer editors do not include the line break in a shift-end operation. Easy enough to fix, already in the queue for next update.

**Comment by Androthi** [comment]
fixed in 0.8.11

**Comment by char101** [comment]
Thank you.
