### ISSUE TITLE
bug: Kill line Ctrl+\

### ISSUE THREAD

**Issue by cluelessguy836** [Androthi/SavageEd#13]
Kill line keyboard shortcut Ctrl+\ is not working for me. Using the feature from the menu works.

**Comment by Androthi** [comment]
I can't seem to reproduce this bug. Are you using the backslash key that's next to the Enter key or the one on the num pad?
This only works with the one above the enter key, but perhaps I should include the numpad as well.

**Comment by Androthi** [comment]
I can't seem to reproduce this bug. Do you have an extended keyboard that has a backslash key in addition to the one above the enter key?

**Comment by cluelessguy836** [comment]
My keyboard layout is like this. I am using the backslash next to the left shift.

**Comment by Androthi** [comment]
please grab the 0.10.51 from prerelease to test if the backslash key next to the left shift key (right shift on some laptops) works to cut the line.

**Comment by cluelessguy836** [comment]
It's working perfectly  now. The issue has been resolved.
