### ISSUE TITLE
Pressing Ctrl+V and enter rapidly

### ISSUE THREAD

**Issue by cluelessguy836** [Androthi/SavageEd#14]
When I press ctrl+v and enter rapidly, SavageEd first pastes the text and then the enter moves the pasted text one line below while the blinking text cursor remains where it originally was.

**Comment by Androthi** [comment]
that's because you have your finger still on ctrl, so you're pressing ctrl+enter which adds an empty line above.

**Comment by cluelessguy836** [comment]
OK. I wasn't aware that Ctrl+Enter was an intended feature to add a line below.
