### ISSUE TITLE
feature request : support utf8 encoding 

### ISSUE THREAD

**Issue by tablecell** [Androthi/SavageEd#3]
open file with utf8 encoding is mess up

**Comment by Androthi** [comment]
SavageEd is not internally designed to support unicode. It supports some unicode by accident, particularly (I think) when interacting with the riched directly.

As I was beginning to finalize SavageEd for end of development cycle, I'm currently not considering features that would require large internal changes (though I'm not immune to persuasion).

To support UTF8 (it might be better to support UCS2, as I think richedit does this internally), the changes needed that I can think of directly are:
* the 2 edit controls in the Find dialog need to be replaced with richedit controls to allow find/replace of unicode text.
* scan.pfind in hidelib needs to be changed for a unicode version to use pattern find (maybe!).
* anything that uses HLA strings will probably break. there is no internal or library support for unicode in HLA, these functions would have to be written from scratch, or all functions that use HLA strings have to be discarded.

**Comment by tablecell** [comment]
how about  use dll from uchardet   contributed  by  https://github.com/BYVoid/uchardet

call uchardet_get_charset to   get file  encoding    
render by  RichEdit50W  with   LoadLibrary(TEXT("Msftedit.dll"));

**Comment by Androthi** [comment]
I don't plan on adding 3rd party DLLs to the distribution. And I don't
think an encoding detector is necessary. The rendering part is not the
problem. SavageEd can render unicode right now, just copy and paste into
it. The work is in getting the unicode to work with all the internal
functionality.
