### ISSUE TITLE
double click on word  to select word but select right single quote 

### ISSUE THREAD

**Issue by tablecell** [Androthi/SavageEd#9]
'hello'  world

double click   hello  want select hello but select right single quote

**Comment by Androthi** [comment]
This is odd behavior. I loaded a very old version of SavageEd and the same thing is still there from the start. It seems to be the way the richedit control handles double clicking on a single quoted word. Possibly a bug in richedit itself, like the margin issue.

Not sure how to go about fixing it. I will probably have to add a special check on double click to see if it's a single quoted single word, and select the proper text manually. ugh. I'll have to think about this one.

**Comment by Androthi** [comment]
I have decided to do a hack fix of this bug as I can't change the source of richedit itself.
In version 0.10.35 release, you can now double click a single quoted string 'hello' and it will select only the word hello.
As a result of this hack fix, you can no longer double click on the end quote to select the end quote and any following spaces.
